language: python
python:
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install -r requirements-test.txt
  - pip install -r requirements.txt
before_script:
  - mkdir -p tests/_coverage
script:
  - py.test tests/ --cov watson --cov-report term-missing
after_success:
  - coveralls --verbose
