language: python
python:
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install -r requirements.txt
before_script:
    - mkdir -p tests/_coverage
script:
    - py.test tests/ --cov watson --cov-report term-missing
after_success:
    - coveralls --verbose
